<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Squirrel-Helper" name="Default test" tests="5" failures="1" timestamp="11 Jun 2014 19:12:43 GMT" time="25.279" errors="0">
  <testcase name="testContactCreationWithValidData" time="3.7" classname="com.example.tests.ContactCreationTests"/>
  <testcase name="testContactCreationWithValidData" time="3.261" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [17]: ContactData [first_name=test-313009325, last_name=test497718685, home_phone=358750420, email=test-2098242072] != ContactData [first_name=test1878025546, last_name=test330486432, home_phone=1523084472, email=test160940399] expected [ContactData [first_name=test-313009325, last_name=test497718685, home_phone=358750420, email=test-2098242072]] but found [ContactData [first_name=test1878025546, last_name=test330486432, home_phone=1523084472, email=test160940399]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [17]: ContactData [first_name=test-313009325, last_name=test497718685, home_phone=358750420, email=test-2098242072] != ContactData [first_name=test1878025546, last_name=test330486432, home_phone=1523084472, email=test160940399] expected [ContactData [first_name=test-313009325, last_name=test497718685, home_phone=358750420, email=test-2098242072]] but found [ContactData [first_name=test1878025546, last_name=test330486432, home_phone=1523084472, email=test160940399]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testContactCreationWithValidData(ContactCreationTests.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testContactCreationWithValidData -->
  <testcase name="testContactCreationWithValidData" time="3.497" classname="com.example.tests.ContactCreationTests"/>
  <testcase name="testContactCreationWithValidData" time="3.566" classname="com.example.tests.ContactCreationTests"/>
  <testcase name="testContactCreationWithValidData" time="3.696" classname="com.example.tests.ContactCreationTests"/>
</testsuite> <!-- Default test -->
